apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-v1
  labels:
    app: guestbook
    version: "1.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
        version: "1.0"
        razee/watch-resource: "lite"
    spec:
      containers:
      - name: guestbook
        image: ibmcom/guestbook:v1
        ports:
        - name: http-server
          containerPort: 3000
apiVersion: v1
kind: Service
metadata:
  name: guestbook
  labels:
    app: guestbook
    razee/watch-resource: "lite"
spec:
  ports:
  - port: 3000
    targetPort: http-server
    nodePort: 31999
  selector:
    app: guestbook
  type: NodePort
